# -*- coding: utf-8 -*-

"""Shared Script Toolbox UI layout metrics.

These values describe repeated presentation geometry only. Functional limits
such as numeric ranges, runtime row sizes and user-configurable spacing stay
with the owning model or widget.
"""

# Generic layout geometry ---------------------------------------------------
MARGINS_NONE = (0, 0, 0, 0)
INLINE_CONTROL_SPACING = 4
FORM_INLINE_SPACING = 8

# Shared control geometry ---------------------------------------------------
BORDER_RADIUS_CONTROL = 2
BORDER_RADIUS_PANEL = 3
BORDER_RADIUS_CARD = 4

BUTTON_MIN_HEIGHT = 20
BUTTON_PADDING_VERTICAL = 4
BUTTON_PADDING_HORIZONTAL = 8

INPUT_MIN_HEIGHT = 22
INPUT_PADDING_VERTICAL = 2
INPUT_PADDING_HORIZONTAL = 5

LIST_ITEM_MIN_HEIGHT = 20
LIST_ITEM_PADDING_VERTICAL = 3
LIST_ITEM_PADDING_HORIZONTAL = 4

# Tabs ----------------------------------------------------------------------
# Generic tab geometry used by the base stylesheet.
TAB_BORDER_WIDTH = 1
TAB_SELECTED_ACCENT_WIDTH = 2
TAB_PANE_TOP_OFFSET = -1
TAB_PADDING_VERTICAL = 5
TAB_PADDING_HORIZONTAL = 11
TAB_MARGIN_RIGHT = 1

# Runtime toolbox tabs intentionally use denser folder-like proportions while
# keeping normal tab geometry. The overlap closes the Qt4 seam between the
# selected tab and its pane in Maya 2015.
RUNTIME_TAB_MIN_HEIGHT = 18
RUNTIME_TAB_PADDING_VERTICAL = 3
RUNTIME_TAB_PADDING_HORIZONTAL = 9
RUNTIME_TAB_BAR_OFFSET = 0
RUNTIME_TAB_SELECTED_OVERLAP = -1

# Runtime toolbox content grid ----------------------------------------------
# Folder, tab and radio pages share the same inner gutter and vertical rhythm.
# Parameter rows use a stable label column so every control starts on the same
# x-coordinate. Compact Row children intentionally opt out of that fixed label
# width because their sizing is owned by the Row container.
RUNTIME_FOLDER_ROOT_MARGINS = MARGINS_NONE
RUNTIME_FOLDER_ROOT_SPACING = 0
RUNTIME_FOLDER_CONTENT_MARGINS = (8, 6, 8, 6)
RUNTIME_FOLDER_CONTENT_SPACING = 4
# Simple Section uses its header label as the legend that interrupts the top
# frame edge. A zero top inset lets the label surface mask that edge cleanly,
# while the existing 8 px gutter keeps the title away from the left corner.
RUNTIME_SIMPLE_HEADER_MARGINS = (8, 0, 5, 0)
RUNTIME_SIMPLE_HEADER_SPACING = 4
RUNTIME_PARAMETER_ROW_MARGINS = MARGINS_NONE
RUNTIME_PARAMETER_SPACING = 4
RUNTIME_PARAMETER_LABEL_WIDTH = 105
RUNTIME_GROUP_MARGINS = MARGINS_NONE
RUNTIME_GROUP_SPACING = 0

SCROLLBAR_EXTENT = 11
SCROLLBAR_HANDLE_MINIMUM = 24
SCROLLBAR_HANDLE_MARGIN = 2

# Scroll surface compatibility geometry -------------------------------------
# The external frame replaces QAbstractScrollArea borders on Maya/Qt4.
# Keep these pixels as a dedicated compatibility role rather than merging
# them with generic control geometry just because the values currently match.
SCROLL_SURFACE_BORDER_WIDTH = 1
SCROLL_SURFACE_CONTENT_INSET = 1
SCROLL_SURFACE_BORDER_RADIUS = 2

# Technical icon buttons ----------------------------------------------------
ICON_BUTTON_COMPACT_ICON_SIZE = 16
ICON_BUTTON_COMPACT_SIZE = 25
ICON_BUTTON_TOOLBAR_ICON_SIZE = 18
ICON_BUTTON_TOOLBAR_SIZE = 26
ICON_BUTTON_HEADER_ICON_SIZE = 18
ICON_BUTTON_HEADER_SIZE = 28

# Search field --------------------------------------------------------------
SEARCH_FIELD_MIN_HEIGHT = 24
SEARCH_FIELD_PADDING_VERTICAL = 2
SEARCH_FIELD_PADDING_HORIZONTAL = 7
SEARCH_ICON_GLYPH_SIZE = 12
SEARCH_ICON_SIZE = 18
SEARCH_CLEAR_GLYPH_SIZE = 10
SEARCH_CLEAR_SIZE = 20
SEARCH_TEXT_MARGIN_LEFT = 26
SEARCH_TEXT_MARGIN_RIGHT = 30
SEARCH_EDGE_OFFSET = 5
SEARCH_CLEAR_RIGHT_OFFSET = 7

# Application/editor layout geometry -----------------------------------------
EDITOR_ROOT_MARGINS = (8, 8, 8, 8)
EDITOR_ROOT_SPACING = 7
EDITOR_SPLITTER_HANDLE_WIDTH = 2
EDITOR_PANE_MARGINS = (8, 8, 8, 8)
EDITOR_PANE_SPACING = 6
EDITOR_PROPERTY_HOST_MARGINS = (0, 0, 4, 0)
EDITOR_PALETTE_INDENT = 14
EDITOR_TREE_INDENT = 18
EDITOR_BOTTOM_SPACING = 6
EDITOR_BOTTOM_GROUP_SPACING = 4
EDITOR_ACTION_BUTTON_MIN_WIDTH = 78

TOOLBAR_SPACING = 2
TOOLBAR_GROUP_SPACING = 4

TOOLBOX_TOPBAR_MARGINS = (6, 4, 6, 4)
TOOLBOX_TOPBAR_SPACING = 4
TOOLBOX_CONTENT_MARGINS = (6, 6, 6, 6)
TOOLBOX_CONTENT_SPACING = 5

SCRIPT_EDITOR_ROOT_SPACING = 4
SCRIPT_EDITOR_STATUS_SPACING = 4

SHARE_ACTION_SPACING = 6

# Property editor -----------------------------------------------------------
PROPERTY_EDITOR_SPACING = 8
PROPERTY_FORM_HORIZONTAL_SPACING = 8
PROPERTY_FORM_VERTICAL_SPACING = 6
PROPERTY_MULTILINE_TEXT_MIN_HEIGHT = 88

PROPERTY_GROUP_MARGINS = (7, 7, 7, 7)
PROPERTY_GROUP_HORIZONTAL_SPACING = 8
PROPERTY_GROUP_VERTICAL_SPACING = 5

# Trigger editor ------------------------------------------------------------
TRIGGER_PAGE_MARGINS = (2, 3, 2, 2)
TRIGGER_PAGE_SPACING = 4
TRIGGER_PANEL_MARGINS = (5, 5, 5, 5)
TRIGGER_PANEL_SPACING = 3


__all__ = [
    "MARGINS_NONE",
    "INLINE_CONTROL_SPACING",
    "FORM_INLINE_SPACING",
    "BORDER_RADIUS_CONTROL",
    "BORDER_RADIUS_PANEL",
    "BORDER_RADIUS_CARD",
    "BUTTON_MIN_HEIGHT",
    "BUTTON_PADDING_VERTICAL",
    "BUTTON_PADDING_HORIZONTAL",
    "INPUT_MIN_HEIGHT",
    "INPUT_PADDING_VERTICAL",
    "INPUT_PADDING_HORIZONTAL",
    "LIST_ITEM_MIN_HEIGHT",
    "LIST_ITEM_PADDING_VERTICAL",
    "LIST_ITEM_PADDING_HORIZONTAL",
    "TAB_BORDER_WIDTH",
    "TAB_SELECTED_ACCENT_WIDTH",
    "TAB_PANE_TOP_OFFSET",
    "TAB_PADDING_VERTICAL",
    "TAB_PADDING_HORIZONTAL",
    "TAB_MARGIN_RIGHT",
    "RUNTIME_TAB_MIN_HEIGHT",
    "RUNTIME_TAB_PADDING_VERTICAL",
    "RUNTIME_TAB_PADDING_HORIZONTAL",
    "RUNTIME_TAB_BAR_OFFSET",
    "RUNTIME_TAB_SELECTED_OVERLAP",
    "RUNTIME_FOLDER_ROOT_MARGINS",
    "RUNTIME_FOLDER_ROOT_SPACING",
    "RUNTIME_FOLDER_CONTENT_MARGINS",
    "RUNTIME_FOLDER_CONTENT_SPACING",
    "RUNTIME_SIMPLE_HEADER_MARGINS",
    "RUNTIME_SIMPLE_HEADER_SPACING",
    "RUNTIME_PARAMETER_ROW_MARGINS",
    "RUNTIME_PARAMETER_SPACING",
    "RUNTIME_PARAMETER_LABEL_WIDTH",
    "RUNTIME_GROUP_MARGINS",
    "RUNTIME_GROUP_SPACING",
    "SCROLLBAR_EXTENT",
    "SCROLLBAR_HANDLE_MINIMUM",
    "SCROLLBAR_HANDLE_MARGIN",
    "SCROLL_SURFACE_BORDER_WIDTH",
    "SCROLL_SURFACE_CONTENT_INSET",
    "SCROLL_SURFACE_BORDER_RADIUS",
    "ICON_BUTTON_COMPACT_ICON_SIZE",
    "ICON_BUTTON_COMPACT_SIZE",
    "ICON_BUTTON_TOOLBAR_ICON_SIZE",
    "ICON_BUTTON_TOOLBAR_SIZE",
    "ICON_BUTTON_HEADER_ICON_SIZE",
    "ICON_BUTTON_HEADER_SIZE",
    "SEARCH_FIELD_MIN_HEIGHT",
    "SEARCH_FIELD_PADDING_VERTICAL",
    "SEARCH_FIELD_PADDING_HORIZONTAL",
    "SEARCH_ICON_GLYPH_SIZE",
    "SEARCH_ICON_SIZE",
    "SEARCH_CLEAR_GLYPH_SIZE",
    "SEARCH_CLEAR_SIZE",
    "SEARCH_TEXT_MARGIN_LEFT",
    "SEARCH_TEXT_MARGIN_RIGHT",
    "SEARCH_EDGE_OFFSET",
    "SEARCH_CLEAR_RIGHT_OFFSET",
    "EDITOR_ROOT_MARGINS",
    "EDITOR_ROOT_SPACING",
    "EDITOR_SPLITTER_HANDLE_WIDTH",
    "EDITOR_PANE_MARGINS",
    "EDITOR_PANE_SPACING",
    "EDITOR_PROPERTY_HOST_MARGINS",
    "EDITOR_PALETTE_INDENT",
    "EDITOR_TREE_INDENT",
    "EDITOR_BOTTOM_SPACING",
    "EDITOR_BOTTOM_GROUP_SPACING",
    "EDITOR_ACTION_BUTTON_MIN_WIDTH",
    "TOOLBAR_SPACING",
    "TOOLBAR_GROUP_SPACING",
    "TOOLBOX_TOPBAR_MARGINS",
    "TOOLBOX_TOPBAR_SPACING",
    "TOOLBOX_CONTENT_MARGINS",
    "TOOLBOX_CONTENT_SPACING",
    "SCRIPT_EDITOR_ROOT_SPACING",
    "SCRIPT_EDITOR_STATUS_SPACING",
    "SHARE_ACTION_SPACING",
    "PROPERTY_EDITOR_SPACING",
    "PROPERTY_FORM_HORIZONTAL_SPACING",
    "PROPERTY_FORM_VERTICAL_SPACING",
    "PROPERTY_MULTILINE_TEXT_MIN_HEIGHT",
    "PROPERTY_GROUP_MARGINS",
    "PROPERTY_GROUP_HORIZONTAL_SPACING",
    "PROPERTY_GROUP_VERTICAL_SPACING",
    "TRIGGER_PAGE_MARGINS",
    "TRIGGER_PAGE_SPACING",
    "TRIGGER_PANEL_MARGINS",
    "TRIGGER_PANEL_SPACING",
]
