# -*- coding: utf-8 -*-

"""Shared Script Toolbox UI layout metrics.

These values describe repeated presentation geometry only. Functional limits
such as numeric ranges, runtime row sizes and user-configurable spacing stay
with the owning model or widget.
"""

# Generic layout geometry ---------------------------------------------------
MARGINS_NONE = (0, 0, 0, 0)
INLINE_CONTROL_SPACING = 4
FORM_INLINE_SPACING = 8

# Shared control geometry ---------------------------------------------------
BORDER_RADIUS_CONTROL = 2
BORDER_RADIUS_PANEL = 3
BORDER_RADIUS_CARD = 4

BUTTON_MIN_HEIGHT = 20
BUTTON_PADDING_VERTICAL = 4
BUTTON_PADDING_HORIZONTAL = 8

INPUT_MIN_HEIGHT = 22
INPUT_PADDING_VERTICAL = 2
INPUT_PADDING_HORIZONTAL = 5

LIST_ITEM_MIN_HEIGHT = 20
LIST_ITEM_PADDING_VERTICAL = 3
LIST_ITEM_PADDING_HORIZONTAL = 4

TAB_PADDING_VERTICAL = 5
TAB_PADDING_HORIZONTAL = 11
TAB_MARGIN_RIGHT = 1

SCROLLBAR_EXTENT = 11
SCROLLBAR_HANDLE_MINIMUM = 24
SCROLLBAR_HANDLE_MARGIN = 2

# Technical icon buttons ----------------------------------------------------
ICON_BUTTON_COMPACT_ICON_SIZE = 16
ICON_BUTTON_COMPACT_SIZE = 25
ICON_BUTTON_TOOLBAR_ICON_SIZE = 18
ICON_BUTTON_TOOLBAR_SIZE = 26
ICON_BUTTON_HEADER_ICON_SIZE = 18
ICON_BUTTON_HEADER_SIZE = 28

# Search field --------------------------------------------------------------
SEARCH_FIELD_MIN_HEIGHT = 24
SEARCH_FIELD_PADDING_VERTICAL = 2
SEARCH_FIELD_PADDING_HORIZONTAL = 7
SEARCH_ICON_GLYPH_SIZE = 12
SEARCH_ICON_SIZE = 18
SEARCH_CLEAR_GLYPH_SIZE = 10
SEARCH_CLEAR_SIZE = 20
SEARCH_TEXT_MARGIN_LEFT = 26
SEARCH_TEXT_MARGIN_RIGHT = 30
SEARCH_EDGE_OFFSET = 5
SEARCH_CLEAR_RIGHT_OFFSET = 7

# Property editor -----------------------------------------------------------
PROPERTY_EDITOR_SPACING = 8
PROPERTY_FORM_HORIZONTAL_SPACING = 8
PROPERTY_FORM_VERTICAL_SPACING = 6

PROPERTY_GROUP_MARGINS = (7, 7, 7, 7)
PROPERTY_GROUP_HORIZONTAL_SPACING = 8
PROPERTY_GROUP_VERTICAL_SPACING = 5

# Trigger editor ------------------------------------------------------------
TRIGGER_PAGE_MARGINS = (2, 3, 2, 2)
TRIGGER_PAGE_SPACING = 4
TRIGGER_PANEL_MARGINS = (5, 5, 5, 5)
TRIGGER_PANEL_SPACING = 3


__all__ = [
    "MARGINS_NONE",
    "INLINE_CONTROL_SPACING",
    "FORM_INLINE_SPACING",
    "BORDER_RADIUS_CONTROL",
    "BORDER_RADIUS_PANEL",
    "BORDER_RADIUS_CARD",
    "BUTTON_MIN_HEIGHT",
    "BUTTON_PADDING_VERTICAL",
    "BUTTON_PADDING_HORIZONTAL",
    "INPUT_MIN_HEIGHT",
    "INPUT_PADDING_VERTICAL",
    "INPUT_PADDING_HORIZONTAL",
    "LIST_ITEM_MIN_HEIGHT",
    "LIST_ITEM_PADDING_VERTICAL",
    "LIST_ITEM_PADDING_HORIZONTAL",
    "TAB_PADDING_VERTICAL",
    "TAB_PADDING_HORIZONTAL",
    "TAB_MARGIN_RIGHT",
    "SCROLLBAR_EXTENT",
    "SCROLLBAR_HANDLE_MINIMUM",
    "SCROLLBAR_HANDLE_MARGIN",
    "ICON_BUTTON_COMPACT_ICON_SIZE",
    "ICON_BUTTON_COMPACT_SIZE",
    "ICON_BUTTON_TOOLBAR_ICON_SIZE",
    "ICON_BUTTON_TOOLBAR_SIZE",
    "ICON_BUTTON_HEADER_ICON_SIZE",
    "ICON_BUTTON_HEADER_SIZE",
    "SEARCH_FIELD_MIN_HEIGHT",
    "SEARCH_FIELD_PADDING_VERTICAL",
    "SEARCH_FIELD_PADDING_HORIZONTAL",
    "SEARCH_ICON_GLYPH_SIZE",
    "SEARCH_ICON_SIZE",
    "SEARCH_CLEAR_GLYPH_SIZE",
    "SEARCH_CLEAR_SIZE",
    "SEARCH_TEXT_MARGIN_LEFT",
    "SEARCH_TEXT_MARGIN_RIGHT",
    "SEARCH_EDGE_OFFSET",
    "SEARCH_CLEAR_RIGHT_OFFSET",
    "PROPERTY_EDITOR_SPACING",
    "PROPERTY_FORM_HORIZONTAL_SPACING",
    "PROPERTY_FORM_VERTICAL_SPACING",
    "PROPERTY_GROUP_MARGINS",
    "PROPERTY_GROUP_HORIZONTAL_SPACING",
    "PROPERTY_GROUP_VERTICAL_SPACING",
    "TRIGGER_PAGE_MARGINS",
    "TRIGGER_PAGE_SPACING",
    "TRIGGER_PANEL_MARGINS",
    "TRIGGER_PANEL_SPACING",
]
