# -*- coding: utf-8 -*-

"""Shared Script Toolbox UI color palette.

Keep theme colors here so QSS, runtime overrides and Qt compatibility
fallbacks use the same source of truth. Dynamic colors that are part of user
data (for example custom button colors) should stay local to the owning
widget instead of being added to this palette.
"""

# Core surfaces -------------------------------------------------------------
WINDOW_BG = "#292b2e"
CONTENT_BG = WINDOW_BG
PANEL_BG = "#313337"
PROPERTY_BG = PANEL_BG
CONTROL_BG = "#27292c"
LIST_BG = "#27292c"
INPUT_BG = LIST_BG
LIST_ALT_BG = "#2b2d30"
FILTER_BG = "#2d2f33"
STATUS_BG = "#292b2e"
TOOLTIP_BG = "#27292c"
STRUCTURE_FOLDER_BG = "#302d2a"

# Borders / separators -----------------------------------------------------
BORDER_TOPBAR = "#36383c"
BORDER_DARK = "#45484d"
BORDER_PRESSED = "#45484d"
BORDER_INSET = "#36383c"
BORDER_SOFT = "#45484d"
BORDER_PANEL = "#45484d"
BORDER_TAB = "#45484d"
BORDER_DISABLED = "#3b3d41"
BORDER_GROUP = "#45484d"
SEPARATOR = "#45484d"
TOOLTIP_BORDER = "#555960"
HOVER_BORDER = "#62676f"
FOCUS_BORDER = "#a98b68"

# Text ---------------------------------------------------------------------
TEXT_PRIMARY = "#dadde1"
TEXT_STRONG = "#eeeeee"
TEXT_HEADING = "#e2e2e2"
TEXT_PANE_TITLE = "#e0e0e0"
TEXT_BUTTON = "#dadde1"
TEXT_INPUT = "#dadde1"
TEXT_LIST = "#dadde1"
TEXT_MUTED = "#a0a5ad"
TEXT_STATUS = "#8f8f8f"
TEXT_EDITOR_STATUS = "#8c8c8c"
TEXT_HEADER = "#a8a8a8"
TEXT_TAB = "#aeb3bb"
TEXT_TAB_SELECTED = "#f0f0f0"
TEXT_SUBTLE = "#aeb3bb"
TEXT_DISABLED = "#686868"
TEXT_INPUT_DISABLED = "#6f6f6f"
TEXT_ON_ACCENT = "#ffffff"

# Interface Editor structure accents --------------------------------------
TEXT_PALETTE_GROUP = "#bda88f"
TEXT_STRUCTURE_ROW = "#b6c4cf"
TEXT_STRUCTURE_COLUMN = "#c7b7d7"

# Generic controls ---------------------------------------------------------
SCRIPT_BUTTON_BG = "#3f3f3f"
BUTTON_BG = "#414449"
BUTTON_HOVER_BG = "#4b4e54"
BUTTON_PRESSED_BG = "#34363a"
ICON_BUTTON_HOVER_BG = "#414449"
ICON_BUTTON_HOVER_BORDER = "#62676f"
ICON_BUTTON_PRESSED_BG = "#27292c"
LIST_HOVER_BG = "#36383d"

# Runtime semantics derived from the Interface Editor palette -------------
# Runtime and editor now share the same neutral surfaces instead of carrying
# a second blue/green-tinted set of folder colors.
FOLDER_CARD_BG = PANEL_BG
FOLDER_NESTED_BG = PANEL_BG
FOLDER_HEADER_BG = PANEL_BG
FOLDER_HEADER_HOVER_BG = ICON_BUTTON_HOVER_BG
FOLDER_HEADER_PRESSED_BG = BUTTON_PRESSED_BG
FOLDER_HEADER_COLLAPSED_BG = PANEL_BG
FOLDER_NESTED_HEADER_BG = PANEL_BG
FOLDER_NESTED_HEADER_HOVER_BG = ICON_BUTTON_HOVER_BG
FOLDER_NESTED_HEADER_COLLAPSED_BG = PANEL_BG
SIMPLE_SECTION_NESTED_BG = FOLDER_NESTED_BG
BORDER_FOLDER_NESTED = BORDER_GROUP

TEXT_SECTION = TEXT_PRIMARY
TEXT_SECTION_NESTED = TEXT_PRIMARY
TEXT_FOLDER_NESTED = TEXT_PRIMARY
TEXT_FOLDER_HOVER = TEXT_STRONG
TEXT_FOLDER_COLLAPSED = TEXT_SUBTLE

# Accent / selection -------------------------------------------------------
ACCENT = "#b46d35"
SELECTION_BG = "#68462c"
INPUT_SELECTION_BG = "#8b572c"
SELECTION_TEXT = TEXT_ON_ACCENT

# Code editor ---------------------------------------------------------------
CODE_GUTTER_BG = BORDER_DISABLED
CODE_CURRENT_LINE_BG = PANEL_BG
CODE_LINE_NUMBER = "#777777"
SYNTAX_KEYWORD = "#d4a15d"
SYNTAX_STRING = "#b9c66b"
SYNTAX_COMMENT = "#757575"
SYNTAX_NUMBER = "#79a8d7"
SYNTAX_HOST = "#69b5b5"
EXPRESSION_ERROR = "#e28b8b"
TOOLBAR_ICON = TEXT_PRIMARY

# Update / primary action controls ----------------------------------------
UPDATE_BG = "#925426"
UPDATE_BORDER = "#b36b34"
UPDATE_HOVER_BG = "#a7622d"
UPDATE_HOVER_BORDER = "#cc7b3c"
UPDATE_PRESSED_BG = "#7f4720"
UPDATE_DISABLED_BG = "#4a4038"
UPDATE_DISABLED_TEXT = "#8b827a"
UPDATE_DISABLED_BORDER = "#55483e"
ACCEPT_BG = "#9a5826"
ACCEPT_BORDER = "#ba7139"
ACCEPT_HOVER_BG = "#ad652d"
ACCEPT_HOVER_BORDER = "#d18447"

# Tabs / scrolling ---------------------------------------------------------
TAB_HOVER_BG = "#3b3e43"
TAB_SELECTED_BG = BORDER_GROUP
SCROLL_TRACK_BG = CONTENT_BG
SCROLL_HANDLE_BG = "#4b4e54"
SCROLL_HANDLE_HOVER_BG = "#5b6068"
SCROLL_HANDLE_PRESSED_BG = TEXT_MUTED


__all__ = [
    "WINDOW_BG",
    "CONTENT_BG",
    "PANEL_BG",
    "PROPERTY_BG",
    "CONTROL_BG",
    "INPUT_BG",
    "LIST_BG",
    "LIST_ALT_BG",
    "FILTER_BG",
    "STATUS_BG",
    "TOOLTIP_BG",
    "STRUCTURE_FOLDER_BG",
    "BORDER_TOPBAR",
    "BORDER_DARK",
    "BORDER_PRESSED",
    "BORDER_INSET",
    "BORDER_SOFT",
    "BORDER_PANEL",
    "BORDER_TAB",
    "BORDER_DISABLED",
    "BORDER_GROUP",
    "SEPARATOR",
    "TOOLTIP_BORDER",
    "HOVER_BORDER",
    "FOCUS_BORDER",
    "TEXT_PRIMARY",
    "TEXT_STRONG",
    "TEXT_HEADING",
    "TEXT_PANE_TITLE",
    "TEXT_BUTTON",
    "TEXT_INPUT",
    "TEXT_LIST",
    "TEXT_MUTED",
    "TEXT_STATUS",
    "TEXT_EDITOR_STATUS",
    "TEXT_HEADER",
    "TEXT_TAB",
    "TEXT_TAB_SELECTED",
    "TEXT_SUBTLE",
    "TEXT_DISABLED",
    "TEXT_INPUT_DISABLED",
    "TEXT_ON_ACCENT",
    "TEXT_PALETTE_GROUP",
    "TEXT_STRUCTURE_ROW",
    "TEXT_STRUCTURE_COLUMN",
    "SCRIPT_BUTTON_BG",
    "BUTTON_BG",
    "BUTTON_HOVER_BG",
    "BUTTON_PRESSED_BG",
    "ICON_BUTTON_HOVER_BG",
    "ICON_BUTTON_HOVER_BORDER",
    "ICON_BUTTON_PRESSED_BG",
    "LIST_HOVER_BG",
    "FOLDER_CARD_BG",
    "FOLDER_NESTED_BG",
    "FOLDER_HEADER_BG",
    "FOLDER_HEADER_HOVER_BG",
    "FOLDER_HEADER_PRESSED_BG",
    "FOLDER_HEADER_COLLAPSED_BG",
    "FOLDER_NESTED_HEADER_BG",
    "FOLDER_NESTED_HEADER_HOVER_BG",
    "FOLDER_NESTED_HEADER_COLLAPSED_BG",
    "SIMPLE_SECTION_NESTED_BG",
    "BORDER_FOLDER_NESTED",
    "TEXT_SECTION",
    "TEXT_SECTION_NESTED",
    "TEXT_FOLDER_NESTED",
    "TEXT_FOLDER_HOVER",
    "TEXT_FOLDER_COLLAPSED",
    "ACCENT",
    "SELECTION_BG",
    "INPUT_SELECTION_BG",
    "SELECTION_TEXT",
    "CODE_GUTTER_BG",
    "CODE_CURRENT_LINE_BG",
    "CODE_LINE_NUMBER",
    "SYNTAX_KEYWORD",
    "SYNTAX_STRING",
    "SYNTAX_COMMENT",
    "SYNTAX_NUMBER",
    "SYNTAX_HOST",
    "EXPRESSION_ERROR",
    "TOOLBAR_ICON",
    "UPDATE_BG",
    "UPDATE_BORDER",
    "UPDATE_HOVER_BG",
    "UPDATE_HOVER_BORDER",
    "UPDATE_PRESSED_BG",
    "UPDATE_DISABLED_BG",
    "UPDATE_DISABLED_TEXT",
    "UPDATE_DISABLED_BORDER",
    "ACCEPT_BG",
    "ACCEPT_BORDER",
    "ACCEPT_HOVER_BG",
    "ACCEPT_HOVER_BORDER",
    "TAB_HOVER_BG",
    "TAB_SELECTED_BG",
    "SCROLL_TRACK_BG",
    "SCROLL_HANDLE_BG",
    "SCROLL_HANDLE_HOVER_BG",
    "SCROLL_HANDLE_PRESSED_BG",
]
